[package]
name = "argon-runner"
version = "0.1.0"
edition = "2024"

[dependencies]
argon-compiler = { workspace = true }
argon-format = { workspace = true }
argon-io = { workspace = true }
argon-source = { workspace = true }
argon-tube = { workspace = true }
argon-util = { workspace = true }

embedded-io = { workspace = true }
esexpr = { workspace = true }
esexpr-binary = { workspace = true }
hashbrown = { workspace = true }
noble-idl-runtime = { workspace = true }
parse18-runtime = { workspace = true }
walkdir = { workspace = true }

[build-dependencies]
noble-idl-compiler-rust = { workspace = true }

[lints]
workspace = true

[package.metadata.noble-idl.package_mapping]
"argon.backend.metadata" = "backend::metadata"
