[package]
name = "argon-runner"
version = "0.1.0"
edition = "2024"

[features]
default = []
std = [
    "argon-compiler/std",
    "argon-io/std",
    "argon-source/std",
    "argon-tube/std",
    "argon-util/std",
    "embedded-io/std",
    "esexpr/std",
    "esexpr-binary/std",
    "dep:walkdir",
]

[dependencies]
argon-compiler = { path = "../argon-compiler", default-features = false }
argon-format = { workspace = true }
argon-io = { path = "../argon-io", default-features = false }
argon-source = { path = "../argon-source", default-features = false }
argon-tube = { path = "../argon-tube", default-features = false }
argon-util = { path = "../argon-util", default-features = false }

embedded-io = { workspace = true }
esexpr = { workspace = true }
esexpr-binary = { workspace = true, default-features = false }
hashbrown = { workspace = true }
noble-idl-runtime = { workspace = true }
parse18-runtime = { path = "../parse18/parse18-runtime", default-features = false }
walkdir = { workspace = true, optional = true }

[build-dependencies]
noble-idl-compiler-rust = { workspace = true }

[lints]
workspace = true

[package.metadata.noble-idl.package_mapping]
"argon.backend.metadata" = "backend::metadata"
