rules = [
	DisableSyntax,
	Disable,
	MissingFinal,
]

DisableSyntax.noVars = true
//DisableSyntax.noThrows = true
DisableSyntax.noNulls = true
DisableSyntax.noReturns = true
DisableSyntax.noWhileLoops = true
DisableSyntax.noAsInstanceOf = true
DisableSyntax.noIsInstanceOf = true
DisableSyntax.noXml = true
DisableSyntax.noUniversalEquality = true
Disable.symbols = [
	"scala.util.Either.LeftProjection.get",
	"scala.util.Either.RightProjection.get",
	"scala.Option.get",
	"scala.None.get",
	"scala.Predef.any2stringadd",
	"scala.util.Try.get",
	"scala.util.Failure.get",
	"scala.collection.mutable",
	"scala.Option.option2Iterable",
	"java.lang.Object.eq",
	"java.lang.Object.ne",
	"java.lang.Object.toString",
]
