rules = [
	DisableSyntax,
	Disable,
	MissingFinal,
]

DisableSyntax.noVars = true
//DisableSyntax.noThrows = true
DisableSyntax.noNulls = true
DisableSyntax.noReturns = true
DisableSyntax.noWhileLoops = true
DisableSyntax.noAsInstanceOf = true
DisableSyntax.noIsInstanceOf = true
DisableSyntax.noXml = true
DisableSyntax.noUniversalEquality = true
Disable.symbols = [
	"scala.util.Either.LeftProjection.get",
	"scala.util.Either.RightProjection.get",
	"scala.Option.get",
	"scala.None.get",
	"scala.Predef.any2stringadd",
	"scala.util.Try.get",
	"scala.util.Failure.get",
	"scala.collection.mutable",
	"scala.Option.option2Iterable",
	"java.lang.Object.eq",
	"java.lang.Object.ne",
	"java.lang.Object.toString",

	"zio.ZIO.apply",
	"zio.IO.apply",
	"zio.RIO.apply",
	"zio.UIO.apply",
	"zio.URIO.apply",
	"zio.Task.apply",

	"zio.IO.effect",
	"zio.RIO.effect",
	"zio.UIO.effect",
	"zio.URIO.effect",
	"zio.Task.effect",
	"zio.ZManaged.effect",

	"zio.IO.effectTotal",
	"zio.RIO.effectTotal",
	"zio.UIO.effectTotal",
	"zio.URIO.effectTotal",
	"zio.Task.effectTotal",
	"zio.ZManaged.effectTotal",

	"zio.IO.effectSuspend",
	"zio.RIO.effectSuspend",
	"zio.UIO.effectSuspend",
	"zio.URIO.effectSuspend",
	"zio.Task.effectSuspend",

	"zio.IO.effectSuspendTotal",
	"zio.RIO.effectSuspendTotal",
	"zio.UIO.effectSuspendTotal",
	"zio.URIO.effectSuspendTotal",
	"zio.Task.effectSuspendTotal",

	"zio.IO.effectSuspendTotalWith",
	"zio.RIO.effectSuspendTotalWith",
	"zio.UIO.effectSuspendTotalWith",
	"zio.URIO.effectSuspendTotalWith",
	"zio.Task.effectSuspendTotalWith",

	"zio.IO.effectSuspendWith",
	"zio.RIO.effectSuspendWith",
	"zio.UIO.effectSuspendWith",
	"zio.URIO.effectSuspendWith",
	"zio.Task.effectSuspendWith",

	"zio.IO.effectAsync",
	"zio.RIO.effectAsync",
	"zio.UIO.effectAsync",
	"zio.URIO.effectAsync",
	"zio.Task.effectAsync",

	"zio.IO.effectAsyncInterrupt",
	"zio.RIO.effectAsyncInterrupt",
	"zio.UIO.effectAsyncInterrupt",
	"zio.URIO.effectAsyncInterrupt",
	"zio.Task.effectAsyncInterrupt",

	"zio.IO.effectAsyncM",
	"zio.RIO.effectAsyncM",
	"zio.UIO.effectAsyncM",
	"zio.URIO.effectAsyncM",
	"zio.Task.effectAsyncM",

	"zio.IO.effectAsyncMaybe",
	"zio.RIO.effectAsyncMaybe",
	"zio.UIO.effectAsyncMaybe",
	"zio.URIO.effectAsyncMaybe",
	"zio.Task.effectAsyncMaybe",

	"zio.stream.ZStream.fromJavaIteratorTotal",
	"zio.stream.ZStream.fromIterator",
	"zio.stream.ZStream.fromJavaIterator",
	"zio.stream.ZStream.fromIteratorEffect",
	"zio.stream.ZStream.fromJavaIteratorEffect",
	"zio.stream.ZStream.fromIteratorManaged",
	"zio.stream.ZStream.fromJavaIteratorManaged",
	"zio.stream.ZStream.fromFile",


]
