[workspace]
resolver = "3"
members = ["argon-cli", "argon-compiler", "argon-dist", "argon-expr", "argon-format", "argon-format-vm", "argon-io", "argon-opt", "argon-parser", "argon-prover", "argon-tasks", "argon-source", "argon-test-runner", "argon-testcases", "argon-tube", "argon-util", "argon-vm", "argon-z3", "parse18/parse18-lexer-gen", "parse18/parse18-ll-gen", "parse18/parse18-runtime"]

[workspace.package]
version = "0.1.0"
edition = "2024"
publish = false

[workspace.dependencies]
argon-compiler = { path = "argon-compiler" }
argon-util = { path = "argon-util" }
argon-expr = { path = "argon-expr" }
argon-format = { path = "argon-format" }
argon-format-vm = { path = "argon-format-vm" }
argon-io = { path = "argon-io" }
argon-opt = { path = "argon-opt" }
argon-parser = { path = "argon-parser" }
argon-prover = { path = "argon-prover" }
argon-tasks = { path = "argon-tasks" }
argon-source = { path = "argon-source" }
argon-testcases = { path = "argon-testcases" }
argon-test-runner = { path = "argon-test-runner" }
argon-tube = { path = "argon-tube" }
argon-vm = { path = "argon-vm" }
argon-z3 = { path = "argon-z3" }
esexpr = { version = "0.3.1" }
esexpr-binary = { version = "0.3.1" }
noble-idl-compiler-rust = { path = "../noble-idl/langs/rust/backend" }
noble-idl-runtime = { path = "../noble-idl/langs/rust/runtime" }

base64 = "0.22.1"
bitflags = "2.13.0"
clap = { version = "4.6.1", features = ["derive"] }
dashmap = "6.2.1"
dhat = "0.3.3"
derivative = { version = "2.2.0", features = ["use_core"] }
embedded-io = { version = "0.7.1" }
encoding_rs = { version = "0.8.35", features = ["alloc"] }
fs_extra = { version = "1.3.0" }
futures-lite = "2.6.1"
hashbrown = { version = "0.17.1", features = ["default-hasher"] }
libtest-mimic = "0.8.2"
mitsein = { version = "0.9.0", features = ["alloc"] }
num-bigint = { version = "0.4.6" }
num-traits = { version = "0.2.19" }
parse18-lexer-gen = { path = "parse18/parse18-lexer-gen" }
parse18-ll-gen = { path = "parse18/parse18-ll-gen" }
parse18-runtime = { path = "parse18/parse18-runtime" }
percent-encoding = { version = "2.3.2", features = ["alloc"] }
quick-xml = "0.40.1"
rayon = "1.12.0"
regex-syntax = { version = "0.8.10", features = ["unicode"] }
rpds = { version = "1.2.1" }
rstest = "0.26.1"
serde = { version = "1.0.228", features = ["alloc"] }
strum = { version = "0.28.0", features = ["derive"] }
subprocess = "1.1.0"
tempfile = "3.27.0"
toml_edit = { version = "0.25.11", features = ["parse", "serde"] }
unicode-general-category = { version = "1.1.0" }
walkdir = "2.5.0"
windows-sys = "0.61.2"
wasm-bindgen = "0.2.126"
wasm-bindgen-futures = "0.4.78"
walrus = "0.26.5"
wasm-bindgen-cli-support = "0.2.128"
wat = "1.245.1"
z3-sys = { version = "0.11.0", features = ["vendored"] }

[workspace.lints.rust]
macro_use_extern_crate = "deny"
unused_must_use = "deny"

[workspace.lints.clippy]
correctness = { level = "deny", priority = -1 }
suspicious = { level = "deny", priority = -1 }
complexity = { level = "deny", priority = -1 }
perf = { level = "deny", priority = -1 }
style = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
allow_attributes_without_reason = "deny"
as_pointer_underscore = "deny"
as_underscore = "deny"
unwrap_used = "deny"
needless_lifetimes = "allow"
elidable_lifetime_names = "allow"
match_wildcard_for_single_variants = "allow"
single_match_else = "allow"
too_many_lines = "allow"
needless_pass_by_value = "allow"
collapsible_else_if = "allow"
similar_names = "allow"
mismatching_type_param_order = "allow"
ignored_unit_patterns = "allow"
tabs_in_doc_comments = "allow"
wildcard_imports = "allow"
must_use_candidate = "allow"
missing_errors_doc = "allow"
struct_field_names = "allow"
too_many_arguments = "allow"
new_without_default = "allow"
enum_glob_use = "allow"

[profile.small]
inherits = "release"
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
