[workspace]
resolver = "3"
members = ["argon-cli","argon-compiler","argon-expr","argon-format", "argon-io","argon-parser", "argon-prover", "argon-runner", "argon-source","argon-testcases", "argon-tube","argon-util", "parse18/parse18-lexer-gen", "parse18/parse18-ll-gen", "parse18/parse18-runtime"]

[workspace.dependencies]
argon-compiler = { path = "argon-compiler" }
argon-util = { path = "argon-util" }
argon-expr = { path = "argon-expr" }
argon-format = { path = "argon-format" }
argon-io = { path = "argon-io" }
argon-parser = { path = "argon-parser" }
argon-prover = { path = "argon-prover" }
argon-runner = { path = "argon-runner" }
argon-source = { path = "argon-source" }
argon-tube = { path = "argon-tube" }
esexpr = { path = "../esexpr/rust/esexpr", default-features = false }
esexpr-binary = { path = "../esexpr/rust/esexpr-binary", default-features = false }
noble-idl-compiler-rust = { path = "../noble-idl/langs/rust/backend" }
noble-idl-runtime = { path = "../noble-idl/langs/rust/runtime" }

bitflags = "2.11.1"
clap = { version = "4.6.1", features = ["derive"] }
dashmap = "6.2.1"
derivative = "2.2.0"
embedded-io = { version = "0.6.1", default-features = false }
encoding_rs = { version = "0.8.35", default-features = false, features = ["alloc"] }
hashbrown = { version = "0.16.1", default-features = false, features = ["default-hasher"] }
mitsein = { version = "0.9.0", default-features = false, features = ["alloc"] }
num-bigint = { version = "0.4.6", default-features = false }
num-traits = { version = "0.2.19", default-features = false }
parse18-lexer-gen = { path = "parse18/parse18-lexer-gen" }
parse18-ll-gen = { path = "parse18/parse18-ll-gen" }
parse18-runtime = { path = "parse18/parse18-runtime" }
percent-encoding = { version = "2.3.2", default-features = false, features = ["alloc"] }
quick-xml = "0.40.1"
rayon = "1.12.0"
regex-syntax = { version = "0.8.10", default-features = false, features = ["unicode"] }
rpds = { version = "1.2.1", default-features = false }
rstest = "0.26.1"
serde = { version = "1.0.228", default-features = false, features = ["alloc"] }
strum = { version = "0.28.0", features = ["derive"] }
unicode-general-category = "1.1.0"
walkdir = "2.5.0"

[workspace.lints.rust]
macro_use_extern_crate = "deny"
unused_must_use = "deny"

[workspace.lints.clippy]
correctness = { level = "deny", priority = -1 }
suspicious = { level = "deny", priority = -1 }
complexity = { level = "deny", priority = -1 }
perf = { level = "deny", priority = -1 }
style = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
allow_attributes_without_reason = "deny"
as_pointer_underscore = "deny"
as_underscore = "deny"
unwrap_used = "deny"
needless_lifetimes = "allow"
elidable_lifetime_names = "allow"
match_wildcard_for_single_variants = "allow"
single_match_else = "allow"
too_many_lines = "allow"
needless_pass_by_value = "allow"
collapsible_else_if = "allow"
similar_names = "allow"
mismatching_type_param_order = "allow"
ignored_unit_patterns = "allow"
tabs_in_doc_comments = "allow"
wildcard_imports = "allow"
must_use_candidate = "allow"
missing_errors_doc = "allow"
struct_field_names = "allow"
too_many_arguments = "allow"
new_without_default = "allow"
enum_glob_use = "allow"
