[package]
name = "argon-parser"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
argon-util = { workspace = true }
encoding_rs = { workspace = true }
parse18-runtime = { workspace = true }
unicode-general-category = { workspace = true }
num-bigint = { workspace = true }
num-traits = { workspace = true }

[dev-dependencies]
argon-testcases = { path = "../argon-testcases" }
rstest = { workspace = true }

[build-dependencies]
parse18-lexer-gen = { workspace = true }
parse18-ll-gen = { workspace = true }
strum = { workspace = true }
