[package]
name = "argon-tasks"
version = "0.1.0"
edition = "2024"

[dependencies]
argon-compiler = { workspace = true }
argon-format = { workspace = true }
argon-format-vm = { workspace = true }
argon-io = { workspace = true }
argon-opt = { workspace = true }
argon-source = { workspace = true }
argon-tube = { workspace = true }
argon-util = { workspace = true }
argon-vm = { workspace = true }

embedded-io = { workspace = true }
esexpr = { workspace = true }
esexpr-binary = { workspace = true }
hashbrown = { workspace = true }
noble-idl-runtime = { workspace = true }
parse18-runtime = { workspace = true }
walkdir = { workspace = true }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
boa_engine = "0.21.1"
boa_runtime = "0.21.1"

[target.'cfg(target_family = "wasm")'.dependencies]
js-sys = "0.3.81"
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = "0.4.58"

[build-dependencies]
noble-idl-compiler-rust = { workspace = true }

[lints]
workspace = true

[package.metadata.noble-idl.package_mapping]
"argon.backend.metadata" = "backend::metadata"
