[versions]
esexpr = "0.5.1-SNAPSHOT"

[libraries]
esexpr-generator = { module = "dev.argon.esexpr:esexpr-generator", version.ref = "esexpr" }
esexpr-runtime = { module = "dev.argon.esexpr:esexpr-java-runtime", version.ref = "esexpr" }
jawawasm-runtime = { module = "dev.argon.jawawasm:jawawasm-runtime", version = "0.2.0-SNAPSHOT" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version = "5.10.3" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version = "1.10.3" }
jspecify = { module = "org.jspecify:jspecify", version = "1.0.0" }
nobleidl-runtime = { module = "dev.argon.nobleidl:nobleidl-java-runtime", version = "0.2.0-SNAPSHOT" }
picocli = { module = "info.picocli:picocli", version = "4.7.7" }
errorprone = { module = "com.google.errorprone:error_prone_core", version = "2.50.0" }
nullaway = { module = "com.uber.nullaway:nullaway", version = "0.14.0" }

[plugins]
errorprone = { id = "net.ltgt.errorprone", version = "5.1.0" }
