[project]
inputFiles = [ "src/**/*.argon" ]

[compiler-options]
moduleName = "Argon.Core"

[argon-module]
referenceModule = "Argon.Core.armodule"

[js]
# referenceModule = "js/Argon.Core.armodule"
outputFile = "js/Argon.Core.js"

[js.extern]
Int_to_s = """

function() {
	return createString(this[intValueSymbol].toString());
}

"""

puts = """

function ([s]) {
	console.log(s[stringValueSymbol]);
	return unitValue;
}

"""

[js.inject]
before = """

export const classConstructorSymbol = Symbol();

function createMethods(methodDescriptions, methods) {
	for(const description of methodDescriptions) {
		const methodInfo = Object.create(null);
		methodInfo.symbol = Symbol();
		methodInfo.value = description.value;
		Object.freeze(methodInfo)
		methods[description.descriptor] = methodInfo;
	}
}

export function createTrait(creator) {
	const trait = Object.create(null);

	trait.marker = Symbol();

	lazyProperty(trait, "baseTraits", function() {
		return creator.baseTraits || [];
	});

	const methods = Object.create(null);
	if(creator.methods) createMethods(creator.methods, methods);
	trait.methods = Object.freeze(methods);

	return Object.freeze(trait);
}

export function createClass(creator) {
	const cls = Object.create(null);


	lazyProperty(cls, "constructor", function() {

		const vtable = creator.vtable;

		return createClassConstructor(creator.baseClass, ctorMap, function(proto) {
			const implTraits = creator.baseTraits;
			if(implTraits) {
				for(const trait of implTraits) {
					implementTrait(proto, trait);
				}
			}
			implementMethods(proto, vtable);
		});
	});

	const ctors = Object.create(null);
	const ctorMap = Object.create(null);
	if(creator.constructors) {
		for(const ctor of creator.constructors) {
			const ctorInfo = Object.create(null);
			ctorInfo.symbol = Symbol();
			ctors[ctor.descriptor] = Object.freeze(ctorInfo);
			ctorMap[ctorInfo.symbol] = ctor.value;
		}
	}
	cls.constructors = Object.freeze(ctors);
	Object.freeze(ctorMap);

	const fields = Object.create(null);
	if(creator.fields) {
		for(const field of creator.fields) {
			const fieldInfo = Object.create(null);
			fieldInfo.symbol = Symbol();
			fields[field.name] = Object.freeze(fieldInfo);
		}
	}
	cls.fields = fields;

	const methods = Object.create(null);
	if(creator.methods) createMethods(creator.methods, methods);
	cls.methods = Object.freeze(methods);

	const clsStatic = Object.create(null);
	const staticMethods = Object.create(null);
	if(creator.staticMethods) createMethods(creator.staticMethods, staticMethods);
	clsStatic.methods = Object.freeze(staticMethods);
	cls.static = clsStatic;

	cls.create = function() {
		const clsObj = Object.create(null);
		for(const desc in this.static.methods) {
			const methodInfo = this.static.methods[desc];
			clsObj[methodInfo.symbol] = methodInfo.value;
		}
		return clsObj;
	};

	return Object.freeze(cls);
}

export function createDataConstructor(creator) {
	const cls = Object.create(null);

	lazyProperty(cls, "constructor", function() {

		const vtable = creator.vtable;
		const ctor = creator.constructor;

		function func(...args) {
			ctor.call(this, ...args);
		}

		func.prototype = Object.create(null);

		implementTrait(func.prototype, creator.instanceType);
		implementMethods(func.prototype, vtable);

		Object.freeze(func.prototype);
		Object.freeze(func);
	});


	const parameters = Object.create(null);
	if(creator.parameters) {
		for(const parameter of creator.parameters) {
			const paramInfo = Object.create(null);
			paramInfo.symbol = Symbol();
			parameters[parameter.name] = Object.freeze(paramInfo);
		}
	}
	cls.parameters = parameters;

	const methods = Object.create(null);
	if(creator.methods) createMethods(creator.methods, methods);
	cls.methods = Object.freeze(methods);

	return Object.freeze(cls);
}

function lazyProperty(obj, name, valueFunc) {
	let value;
	Object.defineProperty(obj, name, {
		get() {
			if(value === undefined) {
				value = valueFunc();
			}
			return value;
		}
	});
}

function createClassConstructor(baseClass, ctors, init) {
	const func = function(ctorId, ...args) {
		ctors[ctorId].call(this, ...args);
	};

	if(baseClass) func.prototype = Object.create(baseClass.constructor);
	else func.prototype = Object.create(null);

	init(func.prototype);
	Object.freeze(func.prototype);
	return Object.freeze(func);
}

function implementTrait(obj, trait) {
	if(trait.marker in obj) {
		return;
	}

	obj[trait.marker] = true;
	for(const baseTrait of trait.baseTraits) {
		implementTrait(obj, baseTrait);
	}
}

function implementMethods(obj, vtable) {
	for(const entry of vtable) {
		obj[entry.symbol] = entry.value;
	}
}


const stringValueSymbol = Symbol();
const intValueSymbol = Symbol();
export const boolValueSymbol = Symbol();


"""

after = """

export const unitValue = Object.freeze(Object.create(classes["Ar.Unit:"].constructor.prototype));

export function createString(str) {
	const obj = Object.create(classes["Ar.String:"].constructor.prototype);
	obj[stringValueSymbol] = str;
	return Object.freeze(obj);
};

export function createInt(i) {
	const obj = Object.create(classes["Ar.Int:"].constructor.prototype);
	obj[intValueSymbol] = i;
	return Object.freeze(obj);
}

export function createBool(b) {
	const obj = Object.create(classes["Ar.Bool:"].constructor.prototype);
	obj[boolValueSymbol] = b;
	return Object.freeze(obj);
}

export function addInt(a, b) {
	return createInt(a[intValueSymbol] + b[intValueSymbol]);
}

export function subInt(a, b) {
	return createInt(a[intValueSymbol] - b[intValueSymbol]);
}

export function mulInt(a, b) {
	return createInt(a[intValueSymbol] * b[intValueSymbol]);
}

export function intEqual(a, b) {
	return createBool(a[intValueSymbol] === b[intValueSymbol]);
}


"""
