[project]
inputFiles = [ "src/**/*.argon" ]

[compiler-options]
moduleName = "Argon.Core"

[backend.argon-module.output]
referenceModule = "bin/Argon.Core.armodule"

[backend.js]
extern = [ "js/extern.js" ]

[backend.js.inject]
before = "js/inject_before.js"
after = "js/inject_after.js"

[backend.js.output]
# referenceModule = "bin/js/Argon.Core.armodule"
outputFile = "bin/js/Argon.Core.js"
