[project]
inputFiles = [ "src/*.argon" ]

[compiler-options]
moduleName = "Argon.Core"

[argon-module]
referenceModule = "Argon.Core.armodule"

[js]
# referenceModule = "js/Argon.Core.armodule"
outputFile = "js/Argon.Core.js"

[js.extern]
Int_to_s = """

function() {
    throw new Error("Not Implemented")
}

"""

puts = """

function(s) {
    throw new Error("Not Implemented")
}

"""


