[package]
name = "argon-io"
version = "0.1.0"
edition = "2024"

[features]
default = []
std = ["argon-util/std", "embedded-io/std", "esexpr-binary/std", "parse18-runtime/std"]

[dependencies]
argon-util = { workspace = true }
embedded-io = { workspace = true }
esexpr-binary = { workspace = true }
parse18-runtime = { workspace = true }

[lints]
workspace = true
