use crate::ast::IntLiteralSuffix;
use alloc::boxed::Box;
use num_bigint::BigUint;

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct IntTokenPayload {
    pub value: BigUint,
    pub suffix: IntLiteralSuffix,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum TokenCategory {
    Error,
    EndOfFile,
    StringStart,
    StringEnd,
    StringText,
    StringInterpolationStart,
    IntToken,
    Identifier,
    NewLine,
    Semicolon,
    KwArgonBuiltin,
    KwDef,
    KwProc,
    KwDo,
    KwEnd,
    KwLet,
    KwVal,
    KwMut,
    KwUse,
    KwShared,
    KwModule,
    KwRecord,
    KwEnum,
    KwTrait,
    KwInstance,
    KwNew,
    KwWith,
    KwTrue,
    KwFalse,
    KwAs,
    KwIs,
    KwImport,
    KwExport,
    KwPublic,
    KwProtected,
    KwPrivate,
    KwInternal,
    KwFinal,
    KwOverride,
    KwVirtual,
    KwIf,
    KwThen,
    KwElse,
    KwElsif,
    KwMatch,
    KwCase,
    KwLoop,
    KwWhile,
    KwBreak,
    KwReturn,
    KwNext,
    KwRedo,
    KwRetry,
    KwErased,
    KwToken,
    KwWitness,
    KwInline,
    KwArgonUnsafeAssumePure,
    KwAbstract,
    KwType,
    KwBigType,
    KwUnderscore,
    KwExtern,
    KwRaise,
    KwBegin,
    KwRescue,
    KwFinally,
    KwRequires,
    KwEnsures,
    KwMaintains,
    KwAssert,
    KwSummon,
    KwResult,
    KwExtension,
    KwInverse,
    KwUpdate,
    KwOperator,
    KwUnary,
    KwBoxed,
    KwBox,
    KwUnbox,
    KwFn,
    OpLogicalAnd,
    OpLogicalOr,
    OpEquals,
    OpNotEquals,
    OpLessThanEq,
    OpGreaterThanEq,
    OpShiftLeft,
    OpShiftRight,
    OpAssign,
    OpDotDot,
    OpStarStar,
    OpLogicalNot,
    OpPlus,
    OpMinus,
    OpStar,
    OpMul,
    OpSlash,
    OpDiv,
    OpBitAnd,
    OpBitOr,
    OpBitXor,
    OpBitNot,
    OpLessThan,
    OpGreaterThan,
    SymColonColon,
    OpArrow,
    OpFatArrow,
    OpConcat,
    OpPropEqual,
    OpPropDisjunction,
    OpPropConjunction,
    SymColon,
    SymDot,
    SymComma,
    SymOpenParen,
    SymCloseParen,
    SymOpenBracket,
    SymCloseBracket,
    SymOpenCurly,
    SymCloseCurly,
    SymPipe,
    SymAt,
    SymSingleQuote,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum BinaryOperator {
    LogicalAnd,
    LogicalOr,
    Equal,
    NotEqual,
    LessThanEq,
    GreaterThanEq,
    ShiftLeft,
    ShiftRight,
    Plus,
    Minus,
    Mul,
    Div,
    BitAnd,
    BitOr,
    BitXOr,
    LessThan,
    GreaterThan,
    Concat,
    PropEqual,
    PropDisjunction,
    PropConjunction,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum UnaryOperator {
    LogicalNot,
    Plus,
    Minus,
    BitNot,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Modifier {
    Public,
    Protected,
    Private,
    Internal,
    Final,
    Override,
    Virtual,
    Erased,
    Token,
    Witness,
    Inline,
    ArgonUnsafeAssumePure,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum Token {
    Error(Box<str>),
    EndOfFile,
    StringStart,
    StringEnd,
    StringText(Box<str>),
    StringInterpolationStart,
    IntToken(IntTokenPayload),
    Identifier(Box<str>),
    NewLine,
    Semicolon,
    KwArgonBuiltin,
    KwDef,
    KwProc,
    KwDo,
    KwEnd,
    KwLet,
    KwVal,
    KwMut,
    KwUse,
    KwShared,
    KwModule,
    KwRecord,
    KwEnum,
    KwTrait,
    KwInstance,
    KwNew,
    KwWith,
    KwTrue,
    KwFalse,
    KwAs,
    KwIs,
    KwImport,
    KwExport,
    KwPublic,
    KwProtected,
    KwPrivate,
    KwInternal,
    KwFinal,
    KwOverride,
    KwVirtual,
    KwIf,
    KwThen,
    KwElse,
    KwElsif,
    KwMatch,
    KwCase,
    KwLoop,
    KwWhile,
    KwBreak,
    KwReturn,
    KwNext,
    KwRedo,
    KwRetry,
    KwErased,
    KwToken,
    KwWitness,
    KwInline,
    KwArgonUnsafeAssumePure,
    KwAbstract,
    KwType,
    KwBigType,
    KwUnderscore,
    KwExtern,
    KwRaise,
    KwBegin,
    KwRescue,
    KwFinally,
    KwRequires,
    KwEnsures,
    KwMaintains,
    KwAssert,
    KwSummon,
    KwResult,
    KwExtension,
    KwInverse,
    KwUpdate,
    KwOperator,
    KwUnary,
    KwBoxed,
    KwBox,
    KwUnbox,
    KwFn,
    OpLogicalAnd,
    OpLogicalOr,
    OpEquals,
    OpNotEquals,
    OpLessThanEq,
    OpGreaterThanEq,
    OpShiftLeft,
    OpShiftRight,
    OpAssign,
    OpDotDot,
    OpStarStar,
    OpLogicalNot,
    OpPlus,
    OpMinus,
    OpStar,
    OpMul,
    OpSlash,
    OpDiv,
    OpBitAnd,
    OpBitOr,
    OpBitXor,
    OpBitNot,
    OpLessThan,
    OpGreaterThan,
    SymColonColon,
    OpArrow,
    OpFatArrow,
    OpConcat,
    OpPropEqual,
    OpPropDisjunction,
    OpPropConjunction,
    SymColon,
    SymDot,
    SymComma,
    SymOpenParen,
    SymCloseParen,
    SymOpenBracket,
    SymCloseBracket,
    SymOpenCurly,
    SymCloseCurly,
    SymPipe,
    SymAt,
    SymSingleQuote,
}

impl Token {
    pub fn category(&self) -> TokenCategory {
        match self {
            Token::Error(..) => TokenCategory::Error,
            Token::EndOfFile => TokenCategory::EndOfFile,
            Token::StringStart => TokenCategory::StringStart,
            Token::StringEnd => TokenCategory::StringEnd,
            Token::StringText(..) => TokenCategory::StringText,
            Token::StringInterpolationStart => TokenCategory::StringInterpolationStart,
            Token::IntToken(..) => TokenCategory::IntToken,
            Token::Identifier(..) => TokenCategory::Identifier,
            Token::NewLine => TokenCategory::NewLine,
            Token::Semicolon => TokenCategory::Semicolon,
            Token::KwArgonBuiltin => TokenCategory::KwArgonBuiltin,
            Token::KwDef => TokenCategory::KwDef,
            Token::KwProc => TokenCategory::KwProc,
            Token::KwDo => TokenCategory::KwDo,
            Token::KwEnd => TokenCategory::KwEnd,
            Token::KwLet => TokenCategory::KwLet,
            Token::KwVal => TokenCategory::KwVal,
            Token::KwMut => TokenCategory::KwMut,
            Token::KwUse => TokenCategory::KwUse,
            Token::KwShared => TokenCategory::KwShared,
            Token::KwModule => TokenCategory::KwModule,
            Token::KwRecord => TokenCategory::KwRecord,
            Token::KwEnum => TokenCategory::KwEnum,
            Token::KwTrait => TokenCategory::KwTrait,
            Token::KwInstance => TokenCategory::KwInstance,
            Token::KwNew => TokenCategory::KwNew,
            Token::KwWith => TokenCategory::KwWith,
            Token::KwTrue => TokenCategory::KwTrue,
            Token::KwFalse => TokenCategory::KwFalse,
            Token::KwAs => TokenCategory::KwAs,
            Token::KwIs => TokenCategory::KwIs,
            Token::KwImport => TokenCategory::KwImport,
            Token::KwExport => TokenCategory::KwExport,
            Token::KwPublic => TokenCategory::KwPublic,
            Token::KwProtected => TokenCategory::KwProtected,
            Token::KwPrivate => TokenCategory::KwPrivate,
            Token::KwInternal => TokenCategory::KwInternal,
            Token::KwFinal => TokenCategory::KwFinal,
            Token::KwOverride => TokenCategory::KwOverride,
            Token::KwVirtual => TokenCategory::KwVirtual,
            Token::KwIf => TokenCategory::KwIf,
            Token::KwThen => TokenCategory::KwThen,
            Token::KwElse => TokenCategory::KwElse,
            Token::KwElsif => TokenCategory::KwElsif,
            Token::KwMatch => TokenCategory::KwMatch,
            Token::KwCase => TokenCategory::KwCase,
            Token::KwLoop => TokenCategory::KwLoop,
            Token::KwWhile => TokenCategory::KwWhile,
            Token::KwBreak => TokenCategory::KwBreak,
            Token::KwReturn => TokenCategory::KwReturn,
            Token::KwNext => TokenCategory::KwNext,
            Token::KwRedo => TokenCategory::KwRedo,
            Token::KwRetry => TokenCategory::KwRetry,
            Token::KwErased => TokenCategory::KwErased,
            Token::KwToken => TokenCategory::KwToken,
            Token::KwWitness => TokenCategory::KwWitness,
            Token::KwInline => TokenCategory::KwInline,
            Token::KwArgonUnsafeAssumePure => TokenCategory::KwArgonUnsafeAssumePure,
            Token::KwAbstract => TokenCategory::KwAbstract,
            Token::KwType => TokenCategory::KwType,
            Token::KwBigType => TokenCategory::KwBigType,
            Token::KwUnderscore => TokenCategory::KwUnderscore,
            Token::KwExtern => TokenCategory::KwExtern,
            Token::KwRaise => TokenCategory::KwRaise,
            Token::KwBegin => TokenCategory::KwBegin,
            Token::KwRescue => TokenCategory::KwRescue,
            Token::KwFinally => TokenCategory::KwFinally,
            Token::KwRequires => TokenCategory::KwRequires,
            Token::KwEnsures => TokenCategory::KwEnsures,
            Token::KwMaintains => TokenCategory::KwMaintains,
            Token::KwAssert => TokenCategory::KwAssert,
            Token::KwSummon => TokenCategory::KwSummon,
            Token::KwResult => TokenCategory::KwResult,
            Token::KwExtension => TokenCategory::KwExtension,
            Token::KwInverse => TokenCategory::KwInverse,
            Token::KwUpdate => TokenCategory::KwUpdate,
            Token::KwOperator => TokenCategory::KwOperator,
            Token::KwUnary => TokenCategory::KwUnary,
            Token::KwBoxed => TokenCategory::KwBoxed,
            Token::KwBox => TokenCategory::KwBox,
            Token::KwUnbox => TokenCategory::KwUnbox,
            Token::KwFn => TokenCategory::KwFn,
            Token::OpLogicalAnd => TokenCategory::OpLogicalAnd,
            Token::OpLogicalOr => TokenCategory::OpLogicalOr,
            Token::OpEquals => TokenCategory::OpEquals,
            Token::OpNotEquals => TokenCategory::OpNotEquals,
            Token::OpLessThanEq => TokenCategory::OpLessThanEq,
            Token::OpGreaterThanEq => TokenCategory::OpGreaterThanEq,
            Token::OpShiftLeft => TokenCategory::OpShiftLeft,
            Token::OpShiftRight => TokenCategory::OpShiftRight,
            Token::OpAssign => TokenCategory::OpAssign,
            Token::OpDotDot => TokenCategory::OpDotDot,
            Token::OpStarStar => TokenCategory::OpStarStar,
            Token::OpLogicalNot => TokenCategory::OpLogicalNot,
            Token::OpPlus => TokenCategory::OpPlus,
            Token::OpMinus => TokenCategory::OpMinus,
            Token::OpStar => TokenCategory::OpStar,
            Token::OpMul => TokenCategory::OpMul,
            Token::OpSlash => TokenCategory::OpSlash,
            Token::OpDiv => TokenCategory::OpDiv,
            Token::OpBitAnd => TokenCategory::OpBitAnd,
            Token::OpBitOr => TokenCategory::OpBitOr,
            Token::OpBitXor => TokenCategory::OpBitXor,
            Token::OpBitNot => TokenCategory::OpBitNot,
            Token::OpLessThan => TokenCategory::OpLessThan,
            Token::OpGreaterThan => TokenCategory::OpGreaterThan,
            Token::SymColonColon => TokenCategory::SymColonColon,
            Token::OpArrow => TokenCategory::OpArrow,
            Token::OpFatArrow => TokenCategory::OpFatArrow,
            Token::OpConcat => TokenCategory::OpConcat,
            Token::OpPropEqual => TokenCategory::OpPropEqual,
            Token::OpPropDisjunction => TokenCategory::OpPropDisjunction,
            Token::OpPropConjunction => TokenCategory::OpPropConjunction,
            Token::SymColon => TokenCategory::SymColon,
            Token::SymDot => TokenCategory::SymDot,
            Token::SymComma => TokenCategory::SymComma,
            Token::SymOpenParen => TokenCategory::SymOpenParen,
            Token::SymCloseParen => TokenCategory::SymCloseParen,
            Token::SymOpenBracket => TokenCategory::SymOpenBracket,
            Token::SymCloseBracket => TokenCategory::SymCloseBracket,
            Token::SymOpenCurly => TokenCategory::SymOpenCurly,
            Token::SymCloseCurly => TokenCategory::SymCloseCurly,
            Token::SymPipe => TokenCategory::SymPipe,
            Token::SymAt => TokenCategory::SymAt,
            Token::SymSingleQuote => TokenCategory::SymSingleQuote,
        }
    }
}

pub enum TokenType {
    Token(Token),
    Whitespace,
    DecInteger,
    BinInteger,
    OctInteger,
    HexInteger,
    Identifier,
    InvalidInteger,
}

pub enum StringTokenType {
    LiteralText,
    EscapedBackspace,
    EscapedFormFeed,
    EscapedNewLine,
    EscapedCarriageReturn,
    EscapedTab,
    EscapedVerticalTab,
    EscapedBackslash,
    EscapedSingleQuote,
    EscapedDoubleQuote,
    EscapedHash,
    EscapedOpenBracket,
    EscapedCloseBracket,
    EscapedOpenCurly,
    EscapedCloseCurly,
    EscapedUnicodeCodePoint,
    InterpolationStart,
    EndOfString,
}
