use alloc::boxed::Box;
use num_bigint::BigUint;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum TokenCategory {
    Error,
    EndOfFile,
    StringStart,
    StringEnd,
    StringText,
    StringInterpolationStart,
    IntToken,
    Identifier,
    NewLine,
    SymSemicolon,
    KwArgonBuiltin,
    KwDef,
    KwProc,
    KwDo,
    KwEnd,
    KwLet,
    KwVal,
    KwMut,
    KwModule,
    KwRecord,
    KwEnum,
    KwTrait,
    KwInstance,
    KwNew,
    KwWith,
    KwTrue,
    KwFalse,
    KwAs,
    KwIs,
    KwImport,
    KwExport,
    KwPublic,
    KwProtected,
    KwPrivate,
    KwInternal,
    KwFinal,
    KwOverride,
    KwVirtual,
    KwIf,
    KwThen,
    KwElse,
    KwElsif,
    KwMatch,
    KwCase,
    KwLoop,
    KwWhile,
    KwBreak,
    KwNext,
    KwRedo,
    KwRetry,
    KwErased,
    KwToken,
    KwWitness,
    KwInline,
    KwAbstract,
    KwType,
    KwBigtype,
    KwUnderscore,
    KwExtern,
    KwRaise,
    KwBegin,
    KwRescue,
    KwFinally,
    KwRequires,
    KwEnsures,
    KwMaintains,
    KwAssert,
    KwSummon,
    KwExtension,
    KwInverse,
    KwUpdate,
    KwOperator,
    KwUnary,
    KwBoxed,
    KwBox,
    KwUnbox,
    KwFn,
    OpLogicalAnd,
    OpLogicalOr,
    OpEquals,
    OpNotequals,
    OpLessthaneq,
    OpGreaterthaneq,
    OpShiftleft,
    OpShiftright,
    OpAssign,
    OpDotdot,
    OpStarstar,
    OpLogicalNot,
    OpPlus,
    OpMinus,
    OpStar,
    OpMul,
    OpSlash,
    OpDiv,
    OpBitand,
    OpBitor,
    OpBitxor,
    OpBitnot,
    OpLessthan,
    OpGreaterthan,
    SymColoncolon,
    OpArrow,
    OpFatArrow,
    OpConcat,
    OpPropEqual,
    OpPropDisjunction,
    OpPropConjunction,
    SymColon,
    SymDot,
    SymComma,
    SymOpenparen,
    SymCloseparen,
    SymOpenbracket,
    SymClosebracket,
    SymOpencurly,
    SymClosecurly,
    SymPipe,
    SymAt,
    SymSingleQuote,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum BinaryOperator {
    LogicalAnd,
    LogicalOr,
    Equal,
    NotEqual,
    LessThanEq,
    GreaterThanEq,
    ShiftLeft,
    ShiftRight,
    Plus,
    Minus,
    Mul,
    Div,
    BitAnd,
    BitOr,
    BitXOr,
    LessThan,
    GreaterThan,
    Concat,
    PropEqual,
    PropDisjunction,
    PropConjunction,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum UnaryOperator {
    LogicalNot,
    Plus,
    Minus,
    BitNot,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Modifier {
    Public,
    Protected,
    Private,
    Internal,
    Final,
    Override,
    Virtual,
    Erased,
    Token,
    Witness,
    Inline,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum Token {
    Error { invalid_text: Box<str> },
    EndOfFile,
    StringStart,
    StringEnd,
    StringText { text: Box<str> },
    StringInterpolationStart,
    IntToken { value: BigUint },
    Identifier { name: Box<str> },
    NewLine,
    Semicolon,
    KwArgonBuiltin,
    KwDef,
    KwProc,
    KwDo,
    KwEnd,
    KwLet,
    KwVal,
    KwMut,
    KwModule,
    KwRecord,
    KwEnum,
    KwTrait,
    KwInstance,
    KwNew,
    KwWith,
    KwTrue,
    KwFalse,
    KwAs,
    KwIs,
    KwImport,
    KwExport,
    KwPublic,
    KwProtected,
    KwPrivate,
    KwInternal,
    KwFinal,
    KwOverride,
    KwVirtual,
    KwIf,
    KwThen,
    KwElse,
    KwElsif,
    KwMatch,
    KwCase,
    KwLoop,
    KwWhile,
    KwBreak,
    KwNext,
    KwRedo,
    KwRetry,
    KwErased,
    KwToken,
    KwWitness,
    KwInline,
    KwAbstract,
    KwType,
    KwBigtype,
    KwUnderscore,
    KwExtern,
    KwRaise,
    KwBegin,
    KwRescue,
    KwFinally,
    KwRequires,
    KwEnsures,
    KwMaintains,
    KwAssert,
    KwSummon,
    KwExtension,
    KwInverse,
    KwUpdate,
    KwOperator,
    KwUnary,
    KwBoxed,
    KwBox,
    KwUnbox,
    KwFn,
    OpLogicalAnd,
    OpLogicalOr,
    OpEquals,
    OpNotequals,
    OpLessthaneq,
    OpGreaterthaneq,
    OpShiftleft,
    OpShiftright,
    OpAssign,
    OpDotdot,
    OpStarstar,
    OpLogicalNot,
    OpPlus,
    OpMinus,
    OpStar,
    OpMul,
    OpSlash,
    OpDiv,
    OpBitand,
    OpBitor,
    OpBitxor,
    OpBitnot,
    OpLessthan,
    OpGreaterthan,
    SymColoncolon,
    OpArrow,
    OpFatArrow,
    OpConcat,
    OpPropEqual,
    OpPropDisjunction,
    OpPropConjunction,
    SymColon,
    SymDot,
    SymComma,
    SymOpenparen,
    SymCloseparen,
    SymOpenbracket,
    SymClosebracket,
    SymOpencurly,
    SymClosecurly,
    SymPipe,
    SymAt,
    SymSingleQuote,
}

impl Token {
    pub fn category(&self) -> TokenCategory {
        match self {
            Token::Error { .. } => TokenCategory::Error,
            Token::EndOfFile => TokenCategory::EndOfFile,
            Token::StringStart => TokenCategory::StringStart,
            Token::StringEnd => TokenCategory::StringEnd,
            Token::StringText { .. } => TokenCategory::StringText,
            Token::StringInterpolationStart => TokenCategory::StringInterpolationStart,
            Token::IntToken { .. } => TokenCategory::IntToken,
            Token::Identifier { .. } => TokenCategory::Identifier,
            Token::NewLine => TokenCategory::NewLine,
            Token::Semicolon => TokenCategory::SymSemicolon,
            Token::KwArgonBuiltin => TokenCategory::KwArgonBuiltin,
            Token::KwDef => TokenCategory::KwDef,
            Token::KwProc => TokenCategory::KwProc,
            Token::KwDo => TokenCategory::KwDo,
            Token::KwEnd => TokenCategory::KwEnd,
            Token::KwLet => TokenCategory::KwLet,
            Token::KwVal => TokenCategory::KwVal,
            Token::KwMut => TokenCategory::KwMut,
            Token::KwModule => TokenCategory::KwModule,
            Token::KwRecord => TokenCategory::KwRecord,
            Token::KwEnum => TokenCategory::KwEnum,
            Token::KwTrait => TokenCategory::KwTrait,
            Token::KwInstance => TokenCategory::KwInstance,
            Token::KwNew => TokenCategory::KwNew,
            Token::KwWith => TokenCategory::KwWith,
            Token::KwTrue => TokenCategory::KwTrue,
            Token::KwFalse => TokenCategory::KwFalse,
            Token::KwAs => TokenCategory::KwAs,
            Token::KwIs => TokenCategory::KwIs,
            Token::KwImport => TokenCategory::KwImport,
            Token::KwExport => TokenCategory::KwExport,
            Token::KwPublic => TokenCategory::KwPublic,
            Token::KwProtected => TokenCategory::KwProtected,
            Token::KwPrivate => TokenCategory::KwPrivate,
            Token::KwInternal => TokenCategory::KwInternal,
            Token::KwFinal => TokenCategory::KwFinal,
            Token::KwOverride => TokenCategory::KwOverride,
            Token::KwVirtual => TokenCategory::KwVirtual,
            Token::KwIf => TokenCategory::KwIf,
            Token::KwThen => TokenCategory::KwThen,
            Token::KwElse => TokenCategory::KwElse,
            Token::KwElsif => TokenCategory::KwElsif,
            Token::KwMatch => TokenCategory::KwMatch,
            Token::KwCase => TokenCategory::KwCase,
            Token::KwLoop => TokenCategory::KwLoop,
            Token::KwWhile => TokenCategory::KwWhile,
            Token::KwBreak => TokenCategory::KwBreak,
            Token::KwNext => TokenCategory::KwNext,
            Token::KwRedo => TokenCategory::KwRedo,
            Token::KwRetry => TokenCategory::KwRetry,
            Token::KwErased => TokenCategory::KwErased,
            Token::KwToken => TokenCategory::KwToken,
            Token::KwWitness => TokenCategory::KwWitness,
            Token::KwInline => TokenCategory::KwInline,
            Token::KwAbstract => TokenCategory::KwAbstract,
            Token::KwType => TokenCategory::KwType,
            Token::KwBigtype => TokenCategory::KwBigtype,
            Token::KwUnderscore => TokenCategory::KwUnderscore,
            Token::KwExtern => TokenCategory::KwExtern,
            Token::KwRaise => TokenCategory::KwRaise,
            Token::KwBegin => TokenCategory::KwBegin,
            Token::KwRescue => TokenCategory::KwRescue,
            Token::KwFinally => TokenCategory::KwFinally,
            Token::KwRequires => TokenCategory::KwRequires,
            Token::KwEnsures => TokenCategory::KwEnsures,
            Token::KwMaintains => TokenCategory::KwMaintains,
            Token::KwAssert => TokenCategory::KwAssert,
            Token::KwSummon => TokenCategory::KwSummon,
            Token::KwExtension => TokenCategory::KwExtension,
            Token::KwInverse => TokenCategory::KwInverse,
            Token::KwUpdate => TokenCategory::KwUpdate,
            Token::KwOperator => TokenCategory::KwOperator,
            Token::KwUnary => TokenCategory::KwUnary,
            Token::KwBoxed => TokenCategory::KwBoxed,
            Token::KwBox => TokenCategory::KwBox,
            Token::KwUnbox => TokenCategory::KwUnbox,
            Token::KwFn => TokenCategory::KwFn,
            Token::OpLogicalAnd => TokenCategory::OpLogicalAnd,
            Token::OpLogicalOr => TokenCategory::OpLogicalOr,
            Token::OpEquals => TokenCategory::OpEquals,
            Token::OpNotequals => TokenCategory::OpNotequals,
            Token::OpLessthaneq => TokenCategory::OpLessthaneq,
            Token::OpGreaterthaneq => TokenCategory::OpGreaterthaneq,
            Token::OpShiftleft => TokenCategory::OpShiftleft,
            Token::OpShiftright => TokenCategory::OpShiftright,
            Token::OpAssign => TokenCategory::OpAssign,
            Token::OpDotdot => TokenCategory::OpDotdot,
            Token::OpStarstar => TokenCategory::OpStarstar,
            Token::OpLogicalNot => TokenCategory::OpLogicalNot,
            Token::OpPlus => TokenCategory::OpPlus,
            Token::OpMinus => TokenCategory::OpMinus,
            Token::OpStar => TokenCategory::OpStar,
            Token::OpMul => TokenCategory::OpMul,
            Token::OpSlash => TokenCategory::OpSlash,
            Token::OpDiv => TokenCategory::OpDiv,
            Token::OpBitand => TokenCategory::OpBitand,
            Token::OpBitor => TokenCategory::OpBitor,
            Token::OpBitxor => TokenCategory::OpBitxor,
            Token::OpBitnot => TokenCategory::OpBitnot,
            Token::OpLessthan => TokenCategory::OpLessthan,
            Token::OpGreaterthan => TokenCategory::OpGreaterthan,
            Token::SymColoncolon => TokenCategory::SymColoncolon,
            Token::OpArrow => TokenCategory::OpArrow,
            Token::OpFatArrow => TokenCategory::OpFatArrow,
            Token::OpConcat => TokenCategory::OpConcat,
            Token::OpPropEqual => TokenCategory::OpPropEqual,
            Token::OpPropDisjunction => TokenCategory::OpPropDisjunction,
            Token::OpPropConjunction => TokenCategory::OpPropConjunction,
            Token::SymColon => TokenCategory::SymColon,
            Token::SymDot => TokenCategory::SymDot,
            Token::SymComma => TokenCategory::SymComma,
            Token::SymOpenparen => TokenCategory::SymOpenparen,
            Token::SymCloseparen => TokenCategory::SymCloseparen,
            Token::SymOpenbracket => TokenCategory::SymOpenbracket,
            Token::SymClosebracket => TokenCategory::SymClosebracket,
            Token::SymOpencurly => TokenCategory::SymOpencurly,
            Token::SymClosecurly => TokenCategory::SymClosecurly,
            Token::SymPipe => TokenCategory::SymPipe,
            Token::SymAt => TokenCategory::SymAt,
            Token::SymSingleQuote => TokenCategory::SymSingleQuote,
        }
    }
}

pub enum TokenType {
    Token(Token),
    Whitespace,
    DecInteger,
    BinInteger,
    OctInteger,
    HexInteger,
    Identifier,
    InvalidInteger,
}

pub enum StringTokenType {
    LiteralText,
    EscapedBackspace,
    EscapedFormFeed,
    EscapedNewLine,
    EscapedCarriageReturn,
    EscapedTab,
    EscapedVerticalTab,
    EscapedBackslash,
    EscapedSingleQuote,
    EscapedDoubleQuote,
    EscapedHash,
    EscapedOpenBracket,
    EscapedCloseBracket,
    EscapedOpenCurly,
    EscapedCloseCurly,
    EscapedUnicodeCodePoint,
    InterpolationStart,
    EndOfString,
}
