[package]
name = "argon-vm-format"
version = "0.1.0"
edition = "2021"

[dependencies]
# num-derive = "0.3.3"
# num-traits = "0.2.15"
itertools = "0.10.3"
# hexf-parse = "0.2.1"
# nom = "7.1.1"
protobuf = "3.2.0"

[build-dependencies]
protobuf-codegen = "3.2.0"
serde_json = "1.0.85"
