[package]
name = "argon-test-runner"
publish = false
edition = "2024"
build = "build.rs"

[[test]]
name = "compiler_tests"
path = "tests/compiler_tests.rs"
harness = false

[[test]]
name = "compiler_tests_dist"
path = "tests/compiler_tests_dist.rs"
harness = false

[[bin]]
name = "compile-testcases"
path = "src/bin/compile_testcases.rs"

[dependencies]
argon-io = { workspace = true }
argon-runner = { workspace = true }
argon-testcases = { workspace = true }
argon-util = { workspace = true }
clap = { workspace = true }
dhat = { version = "0.3.3", optional = true }
libtest-mimic = { workspace = true }
fs_extra = { workspace = true }
hashbrown = { workspace = true }
serde = { workspace = true, features = ["derive"] }
subprocess = { workspace = true }
tempfile = { workspace = true }
toml_edit = { version = "0.25.11", features = ["parse", "serde"] }
walkdir = { workspace = true }

[features]
dhat-heap = ["dep:dhat"]

[lints]
workspace = true
