[package]
name = "argon-tube"
publish = false
edition = "2024"

[features]
default = []
std = ["argon-compiler/std", "argon-expr/std", "argon-format/std", "argon-format-vm/std", "argon-util/std", "argon-vm/std", "embedded-io/std", "esexpr/std", "esexpr-binary/std", "parse18-runtime/std"]

[dependencies]
argon-compiler = { workspace = true }
argon-expr = { workspace = true }
argon-format = { workspace = true }
argon-format-vm = { workspace = true }
argon-util = { workspace = true }
argon-vm = { workspace = true }
embedded-io = { workspace = true }
esexpr = { workspace = true }
esexpr-binary = { workspace = true }
hashbrown = { workspace = true }
mitsein = { workspace = true }
num-bigint = { workspace = true }
num-traits = { workspace = true }
parse18-runtime = { workspace = true }

[lints]
workspace = true
