[package]
name = "argon-util"
publish = false
edition = "2024"

[dependencies]
embedded-io = { workspace = true }
esexpr = { workspace = true }
esexpr-binary = { workspace = true }
parse18-runtime = { workspace = true }
rayon = { workspace = true }
walkdir = { workspace = true }

[lints]
workspace = true
