#!/bin/sh

set -eu

script_dir="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
dist_dir="$(CDPATH= cd -- "$script_dir/.." && pwd)"



os="$(uname -s)"
arch="$(uname -m)"

case "$os:$arch" in
    Linux:x86_64)
        arch_dir=x86_64-unknown-linux-gnu
        ;;
    Linux:i386|Linux:i486|Linux:i586|Linux:i686)
        arch_dir=i686-unknown-linux-gnu
        ;;
    Linux:aarch64|Linux:arm64)
        arch_dir=aarch64-unknown-linux-gnu
        ;;
    *)
        printf 'argonc: unsupported platform: %s %s\n\n' "$os" "$arch" >&2
        exit 1
        ;;
esac

exec "$dist_dir/arch/$arch_dir/argonc" "$@"
