[package]
name = "argon-compiler"
publish = false
edition = "2024"

[features]
test-utils = []

[dependencies]
argon-expr = { workspace = true }
argon-parser = { workspace = true }
argon-util = { workspace = true }
derivative = { workspace = true }
esexpr = { workspace = true }
hashbrown = { workspace = true }
mitsein = { workspace = true }
percent-encoding = { workspace = true }
parse18-runtime = { workspace = true }

[lints]
workspace = true
