[package]
name = "argon-expr"
publish = false
edition = "2024"

[dependencies]
argon-util = { workspace = true }
argon-parser = { workspace = true }
derivative = { workspace = true }
hashbrown = { workspace = true }
mitsein = { workspace = true }
num-bigint = { workspace = true }
parse18-runtime = { workspace = true }

[lints]
workspace = true
