[package]
name = "argon-expr"
publish = false
edition = "2024"

[dependencies]
argon-util = { workspace = true }
argon-parser = { workspace = true }
derivative = { workspace = true }
num-bigint = { workspace = true }
parse18-runtime = { workspace = true }
nonempty-collections = { workspace = true }

[lints]
workspace = true
