[package]
name = "argon-source"
publish = false
edition = "2024"

[dependencies]
argon-compiler = { workspace = true }
argon-expr = { workspace = true }
argon-io = { workspace = true }
argon-parser = { workspace = true }
argon-util = { workspace = true }
hashbrown = { workspace = true }
mitsein = { workspace = true }
num-bigint = { workspace = true }
parse18-runtime = { workspace = true }

[dev-dependencies]
argon-compiler = { workspace = true, features = ["test-utils"] }
embedded-io = { workspace = true }
num-bigint = { workspace = true }
tempfile = { workspace = true }
walkdir = { workspace = true }

[lints]
workspace = true
